services:
  postgres:
    image: postgres:18
    container_name: tienda_next
    restart: always
    environment:
      POSTGRES_DB: tienda_next
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  adminer:
    image: adminer
    restart: always
    ports: ["9900:8080"]
    networks:
      - prisma-network

networks:
  prisma-network:

volumes:
  postgres_data:
